// Mock data de expertos con coordenadas geográficas
export const mockExperts = [
  {
    id: 1,
    name: 'Alex Chen',
    technology: 'React',
    pricePerMinute: 2.5,
    lat: 40.7128,
    lng: -74.0060,
    status: 'online',
    rating: 4.9,
    avatar: '👨‍💻',
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    technology: 'Python',
    pricePerMinute: 3.0,
    lat: 34.0522,
    lng: -118.2437,
    status: 'online',
    rating: 4.8,
    avatar: '👩‍💻',
  },
  {
    id: 3,
    name: 'Marco Silva',
    technology: 'Node.js',
    pricePerMinute: 2.8,
    lat: -23.5505,
    lng: -46.6333,
    status: 'online',
    rating: 5.0,
    avatar: '👨‍💻',
  },
  {
    id: 4,
    name: 'Emma Wilson',
    technology: 'TypeScript',
    pricePerMinute: 3.2,
    lat: 51.5074,
    lng: -0.1278,
    status: 'online',
    rating: 4.7,
    avatar: '👩‍💻',
  },
  {
    id: 5,
    name: 'David Kim',
    technology: 'React',
    pricePerMinute: 2.3,
    lat: 37.5665,
    lng: 126.9780,
    status: 'online',
    rating: 4.9,
    avatar: '👨‍💻',
  },
  {
    id: 6,
    name: 'Lisa Anderson',
    technology: 'Python',
    pricePerMinute: 2.9,
    lat: 59.9343,
    lng: 30.3351,
    status: 'online',
    rating: 4.8,
    avatar: '👩‍💻',
  },
  {
    id: 7,
    name: 'Carlos Mendez',
    technology: 'Vue.js',
    pricePerMinute: 2.6,
    lat: 19.4326,
    lng: -99.1332,
    status: 'online',
    rating: 4.6,
    avatar: '👨‍💻',
  },
  {
    id: 8,
    name: 'Yuki Tanaka',
    technology: 'React',
    pricePerMinute: 2.7,
    lat: 35.6762,
    lng: 139.6503,
    status: 'online',
    rating: 4.9,
    avatar: '👩‍💻',
  },
];

export const technologies = ['React', 'Python', 'Node.js', 'TypeScript', 'Vue.js', 'Angular', 'Java', 'Go'];

